name: mars_osc
description: "Mars Orbital Shipping Company"
publish_to: 'none'

version: 0.9.4+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.2.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/mosco_icon.png"
  # This forces the icon to fill the mask instead of shrinking
  adaptive_icon_background: "assets/mosco_icon.png"
  adaptive_icon_foreground: "assets/mosco_icon.png"

flutter:
  uses-material-design: true